import React from 'react';
import { ViewState } from '../types';
import { Check, Users, MessageCircle, MapPin, DollarSign, TrendingUp, ShoppingBag, Heart, Calendar, ChevronLeft, ArrowRight, Sparkles, Bell } from 'lucide-react';

interface AboutPageProps {
  setViewState: (view: ViewState) => void;
}

export const AboutPage: React.FC<AboutPageProps> = ({ setViewState }) => {
  return (
    <div className="min-h-screen bg-[#15383c] text-gray-200 font-sans pt-20 sm:pt-24 pb-12 sm:pb-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 mb-6 sm:mb-10"><button onClick={() => setViewState(ViewState.LANDING)} className="w-9 h-9 sm:w-10 sm:h-10 bg-white/10 rounded-full flex items-center justify-center text-white hover:bg-white/20 transition-colors touch-manipulation active:scale-95"><ChevronLeft size={20} className="sm:w-6 sm:h-6" /></button></div>
      <div className="max-w-6xl mx-auto px-4 sm:px-6">
        <div className="text-center mb-12 sm:mb-16 md:mb-20"><h1 className="font-heading font-bold text-3xl sm:text-4xl md:text-5xl lg:text-6xl text-white mb-4 sm:mb-6 md:mb-8 leading-tight px-2">About Popera</h1><p className="text-base sm:text-lg md:text-xl lg:text-2xl text-gray-300 font-light max-w-3xl mx-auto leading-relaxed px-4">Popera is Canada's home for pop-up culture. From micro-influencers to creators, organizers, or just friends with an idea — Popera is the easiest way to gather people anywhere: a café, a boutique, a park, a restaurant, or even your living room.</p></div>
        <section className="mb-12 sm:mb-16 md:mb-24"><div className="bg-white/5 p-6 sm:p-8 md:p-12 rounded-[2rem] sm:rounded-[2.5rem] border border-white/10 backdrop-blur-sm relative overflow-hidden"><div className="absolute top-0 right-0 w-64 h-64 bg-[#e35e25] rounded-full blur-[120px] opacity-10 pointer-events-none -translate-y-1/2 translate-x-1/3"></div><div className="relative z-10 flex flex-col md:flex-row gap-6 sm:gap-8 md:gap-10 items-center"><div className="flex-1 space-y-4 sm:space-y-6 text-base sm:text-lg font-light leading-relaxed"><p>Popera lets anyone host real-world pop-up events in minutes.</p></div><div className="flex-1 bg-[#1a454a] p-6 sm:p-8 rounded-2xl sm:rounded-3xl border border-white/5 w-full"><h3 className="font-bold text-white text-lg sm:text-xl mb-3 sm:mb-4 flex items-center gap-2"><Calendar size={18} className="sm:w-5 sm:h-5 text-[#e35e25]" /> Commitment</h3><p className="text-gray-300 mb-4 sm:mb-6 text-sm sm:text-base">Want stronger commitment? Optionally charge a small reservation fee.</p><div className="flex items-center gap-2 sm:gap-3 text-xs sm:text-sm font-bold text-[#e35e25]"><Check size={14} className="sm:w-4 sm:h-4" /><span>Reduce no-shows</span></div></div></div></div></section>
        <section className="mb-12 sm:mb-16 md:mb-24"><div className="text-center mb-8 sm:mb-10 md:mb-12"><span className="inline-block py-1.5 px-4 rounded-full bg-white/5 border border-white/10 text-[#e35e25] text-[10px] sm:text-[11px] font-bold tracking-[0.2em] uppercase mb-3 sm:mb-4">Capabilities</span><h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-heading font-bold text-white">What You Can Do</h2></div><div className="grid md:grid-cols-3 gap-4 sm:gap-6"><div className="bg-[#1a454a] p-6 sm:p-8 rounded-[1.5rem] sm:rounded-[2rem] border border-white/5 hover:-translate-y-2 transition-transform duration-500"><div className="w-10 h-10 sm:w-12 sm:h-12 bg-white/10 rounded-xl sm:rounded-2xl flex items-center justify-center text-[#e35e25] mb-4 sm:mb-6"><ShoppingBag size={20} className="sm:w-6 sm:h-6" /></div><h3 className="text-xl sm:text-2xl font-bold text-white mb-2 sm:mb-3">Sell & Shop</h3><p className="text-gray-400 leading-relaxed text-sm sm:text-base">Turn your audience into real customers in person. Host product drops, flash sales, garage sales, brand demos, or curated second-hand events where people can touch, try, and buy directly from you.</p></div><div className="bg-[#1a454a] p-6 sm:p-8 rounded-[1.5rem] sm:rounded-[2rem] border border-white/5 hover:-translate-y-2 transition-transform duration-500"><div className="w-10 h-10 sm:w-12 sm:h-12 bg-white/10 rounded-xl sm:rounded-2xl flex items-center justify-center text-[#e35e25] mb-4 sm:mb-6"><Users size={20} className="sm:w-6 sm:h-6" /></div><h3 className="text-xl sm:text-2xl font-bold text-white mb-2 sm:mb-3">Connect</h3><p className="text-gray-400 leading-relaxed text-sm sm:text-base">Build genuine relationships with your followers through intimate micro-events. Meet your community in real life, start conversations, and grow loyalty in ways no algorithm ever could.</p></div><div className="bg-[#1a454a] p-6 sm:p-8 rounded-[1.5rem] sm:rounded-[2rem] border border-white/5 hover:-translate-y-2 transition-transform duration-500"><div className="w-10 h-10 sm:w-12 sm:h-12 bg-white/10 rounded-xl sm:rounded-2xl flex items-center justify-center text-[#e35e25] mb-4 sm:mb-6"><Heart size={20} className="sm:w-6 sm:h-6" /></div><h3 className="text-xl sm:text-2xl font-bold text-white mb-2 sm:mb-3">Mobilize</h3><p className="text-gray-400 leading-relaxed text-sm sm:text-base">Gather people for a purpose — from local initiatives and charity drives to spontaneous meetups and community movements. Popera gives you the tools to rally your crowd instantly.</p></div></div></section>
        <section className="mb-12 sm:mb-16 md:mb-24 grid md:grid-cols-2 gap-6 sm:gap-8"><div className="bg-white/5 p-6 sm:p-8 md:p-10 rounded-[2rem] sm:rounded-[2.5rem] border border-white/10"><div className="w-12 h-12 sm:w-14 sm:h-14 bg-[#e35e25] rounded-full flex items-center justify-center text-white mb-6 sm:mb-8 shadow-lg shadow-orange-900/40"><MessageCircle size={24} className="sm:w-7 sm:h-7" /></div><h3 className="text-xl sm:text-2xl font-heading font-bold text-white mb-4 sm:mb-6">Keep the Conversation Going</h3><p className="text-gray-300 text-sm sm:text-base leading-relaxed">Every pop-up includes a built-in group chat so attendees can ask questions, get updates, coordinate arrival, or simply break the ice before meeting. After the event, they can stay connected and continue the conversation.</p></div><div className="bg-white/5 p-6 sm:p-8 md:p-10 rounded-[2rem] sm:rounded-[2.5rem] border border-white/10"><div className="w-12 h-12 sm:w-14 sm:h-14 bg-[#15383c] rounded-full flex items-center justify-center text-white mb-6 sm:mb-8 border border-white/20 shadow-lg"><TrendingUp size={24} className="sm:w-7 sm:h-7" /></div><h3 className="text-xl sm:text-2xl font-heading font-bold text-white mb-4 sm:mb-6">Build a Real-World Following</h3><p className="text-gray-300 text-sm sm:text-base leading-relaxed">Your host profile grows with every pop-up you create. Earn trust through verified hosting, transparent reviews, and consistent engagement. Become a recognizable figure in your local scene — one event at a time.</p></div></section>
        <section className="mb-12 sm:mb-16 md:mb-24 grid md:grid-cols-2 gap-6 sm:gap-8"><div className="bg-white/5 p-6 sm:p-8 md:p-10 rounded-[2rem] sm:rounded-[2.5rem] border border-white/10"><div className="w-12 h-12 sm:w-14 sm:h-14 bg-[#1a454a] rounded-full flex items-center justify-center text-white mb-6 sm:mb-8 border border-white/20 shadow-lg"><Sparkles size={24} className="sm:w-7 sm:h-7" /></div><h3 className="text-xl sm:text-2xl font-heading font-bold text-white mb-4 sm:mb-6">AI-Powered Crowd Dynamics</h3><p className="text-gray-300 text-sm sm:text-base leading-relaxed">Use intelligent suggestions to elevate your pop-ups. Popera's AI analyzes group mood, interests, and engagement patterns to recommend conversation starters, icebreakers, polls, and timing cues that help your crowd feel more connected — without replacing the human touch.</p></div><div className="bg-white/5 p-6 sm:p-8 md:p-10 rounded-[2rem] sm:rounded-[2.5rem] border border-white/10"><div className="w-12 h-12 sm:w-14 sm:h-14 bg-[#e35e25] rounded-full flex items-center justify-center text-white mb-6 sm:mb-8 shadow-lg shadow-orange-900/40"><Bell size={24} className="sm:w-7 sm:h-7" /></div><h3 className="text-xl sm:text-2xl font-heading font-bold text-white mb-4 sm:mb-6">Smart Notifications (SMS & Email)</h3><p className="text-gray-300 text-sm sm:text-base leading-relaxed">Keep your attendees engaged and informed with automated reminders. Popera sends clean and timely SMS and email alerts for event updates, last-minute changes, arrival cues, and post-event follow-ups — helping your pop-ups stay organized and minimizing no-shows.</p></div></section>
        <section className="bg-[#e35e25] rounded-[2rem] sm:rounded-[2.5rem] p-6 sm:p-8 md:p-10 lg:p-16 text-white relative overflow-hidden shadow-2xl shadow-orange-900/30"><div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, black 1px, transparent 0)', backgroundSize: '32px 32px' }}></div><div className="relative z-10 grid md:grid-cols-2 gap-8 sm:gap-10 md:gap-12 items-center"><div><h2 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-heading font-bold mb-4 sm:mb-6">Hosting is Free.</h2><p className="text-base sm:text-lg md:text-xl opacity-90 leading-relaxed font-medium">Public or private. No monthly fees to start.</p></div><div className="bg-black/20 backdrop-blur-md p-6 sm:p-8 rounded-2xl sm:rounded-3xl border border-black/5"><h4 className="font-bold text-base sm:text-lg mb-3 sm:mb-4">How Fees Work</h4><p className="text-white/90 leading-relaxed mb-4 sm:mb-6 text-sm sm:text-base">If you choose to charge a reservation fee, POPERA takes <span className="font-bold bg-white text-[#e35e25] px-1 rounded">10%</span>.</p><button onClick={() => setViewState(ViewState.AUTH)} className="w-full py-3.5 sm:py-4 bg-white text-[#e35e25] rounded-full font-bold hover:bg-gray-100 transition-colors flex items-center justify-center gap-2 text-sm sm:text-base touch-manipulation active:scale-95">Start Hosting <ArrowRight size={16} className="sm:w-[18px] sm:h-[18px]" /></button></div></div></section>
      </div>
    </div>
  );
};